import { cp,mkdir,readFile,writeFile,rm } from 'node:fs/promises';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { copyRuntimeFiles } from './runtime-layout.js';
const source=path.resolve(import.meta.dirname,'..');const staging=path.join(source,'output','release');const target=path.join(staging,'genpet');
const distributable=(file:string)=>!file.split(path.sep).includes('__pycache__')&&!/\.pyc$|\.DS_Store$/.test(file);
// This directory is exclusively generated by this packaging script. A clean stage
// prevents rejected or removed assets from leaking into a later release.
await rm(staging,{recursive:true,force:true});
await mkdir(target,{recursive:true});
await copyRuntimeFiles(source,target);
await cp(path.join(source,'package.json'),path.join(target,'package.json'));
const pkg=JSON.parse(await readFile(path.join(target,'package.json'),'utf8'));
pkg.scripts={start:'node dist/mcp.js',mcp:'node dist/mcp.js','pet:status':'node dist/cli.js status','pet:adopt':'node dist/cli.js adopt','pet:install':'node dist/cli.js install-native'};
await writeFile(path.join(target,'package.json'),JSON.stringify(pkg,null,2));
const marketplace={name:'genpet-local',interface:{displayName:'GenPet local release'},plugins:[{
  name:'genpet',source:{source:'local',path:'./genpet'},
  policy:{installation:'AVAILABLE',authentication:'ON_INSTALL'},category:'Productivity'}]};
await mkdir(path.join(staging,'.agents','plugins'),{recursive:true});
await writeFile(path.join(staging,'.agents','plugins','marketplace.json'),JSON.stringify(marketplace,null,2)+'\n');
const archive=path.join(source,'output',`genpet-${pkg.version}.zip`);await rm(archive,{force:true});
execFileSync('zip',['-qr',archive,'genpet','.agents'],{cwd:staging});console.log(archive);

// Also ship the editable source with tests, without local runs or private state.
const sourceStage=path.join(source,'output','source-release');
const sourceTarget=path.join(sourceStage,'genpet');
await rm(sourceTarget,{recursive:true,force:true});
await mkdir(sourceTarget,{recursive:true});
for(const item of ['src','tests','scripts','assets','skills','vendor','config','docs','.codex-plugin','.mcp.json','.github','.gitignore','LICENSE','README.md','PLUGIN_README.md','CONTRIBUTING.md','THIRD_PARTY_NOTICES.md','package.json','package-lock.json','tsconfig.json'])await cp(path.join(source,item),path.join(sourceTarget,item),{recursive:true,filter:distributable});
const sourceArchive=path.join(source,'output',`genpet-source-${pkg.version}.zip`);
await rm(sourceArchive,{force:true});
execFileSync('zip',['-qr',sourceArchive,'genpet'],{cwd:sourceStage});
console.log(sourceArchive);
